apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/knative/operator/releases/download/knative-v1.14.3/operator.yaml
- knative-serving.yaml
- https://github.com/knative/serving/releases/download/knative-v1.14.1/serving-default-domain.yaml
- logging-pv.yaml
- fluent-bit-collector.yaml
- fluent-bit-configmap.yaml
- config-map-pv.yaml