---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: springofficehours-io
  name: springofficehours-io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: springofficehours-io
  name: springofficehours-io
  namespace: springofficehours-io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: springofficehours-io
  name: gotk-reconciler
  namespace: springofficehours-io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:springofficehours-io:reconciler
  - kind: ServiceAccount
    name: springofficehours-io
    namespace: springofficehours-io