apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: springofficehours-io
  namespace: springofficehours-io
spec:
  interval: 1m
  url: https://github.com/springofficehours-io/flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: springofficehours-io
  namespace: springofficehours-io
spec:
  serviceAccountName: springofficehours-io
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: springofficehours-io
  prune: true