apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: springkubed-io
  namespace: springkubed-io
spec:
  interval: 1m
  url: https://github.com/springkubed-io/flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: springkubed-io
  namespace: springkubed-io
spec:
  serviceAccountName: springkubed-io
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: springkubed-io
  prune: true