---
apiVersion: v1
kind: Namespace
metadata:
  name: dashaun-dev
---
apiVersion: v1
data:
  credentials.json: ${DASHAUN_DEV_TUNNEL_SECRET}
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque