apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashaun-io-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: knative-serving
  interval: 1m
  path: ./tenants/dashaun-io
  prune: true
  retryInterval: 2m0s
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: javagrunt-com-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./tenants/dashaun-io/secrets
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg