apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-javagrunt-com-tenant
  namespace: flux-system
spec:
  interval: 1m
  path: ./tenants/dev-javagrunt-com
  prune: true
  retryInterval: 2m0s
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true