apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: concourse-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: dashaun-io
spec:
  interval: 5m
  chart:
    spec:
      chart: concourse
      sourceRef:
        kind: HelmRepository
        name: concourse-charts
        namespace: flux-system
      interval: 1m
  values:
    concourse:
      web:
        externalUrl: https://dashaun.io/concourse/
      worker:
        runtime: houdini