---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dashaun-io
  name: dashaun-io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dashaun-io
  name: dashaun-io
  namespace: dashaun-io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: dashaun-io
  name: gotk-reconciler
  namespace: dashaun-io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:dashaun-dev:reconciler
  - kind: ServiceAccount
    name: dashaun-io
    namespace: dashaun-io