apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dashaun-io
  namespace: dashaun-io
spec:
  interval: 1m
  url: https://github.com/dashaun-io/flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashaun-io
  namespace: dashaun-io
spec:
  serviceAccountName: dashaun-io
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dashaun-io
  prune: true