---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-domain1-ns
  labels:
    weblogic-operator: enabled
---
apiVersion: v1
data:
  .dockerconfigjson: ${WEBLOGIC_REPO_CREDS}
kind: Secret
metadata:
  name: weblogic-repo-credentials
  namespace: sample-domain1-ns
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  password: ${WEBLOGIC_DOMAIN_ADMIN_PASS}
  username: ${WEBLOGIC_DOMAIN_ADMIN_USER}
kind: Secret
metadata:
  name: sample-domain1-weblogic-credentials
  namespace: sample-domain1-ns
type: Opaque
---
apiVersion: v1
data:
  password: ${WEBLOGIC_DOMAIN_ENCRYPTION_SECRET}
kind: Secret
metadata:
  name: sample-domain1-runtime-encryption-secret
  namespace: sample-domain1-ns
type: Opaque

