---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: concourse
  namespace: concourse
spec:
  ingressClassName: ngrok
  rules:
  - host: kaiju.dashaun.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: concourse-web
            port:
              number: 8080