apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: javagrunt-com-secrets
  namespace: flux-system
spec:
  interval: 1m
  path: ./tenants/javagrunt-com-dev/secrets
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg