apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: javagrunt-com-tenant
  namespace: flux-system
spec:
  dependsOn:
    - name: knative-serving
  interval: 1m
  path: ./tenants/javagrunt-com-dev
  prune: true
  retryInterval: 2m0s
  serviceAccountName: kustomize-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  wait: true