apiVersion: v1
kind: Namespace
metadata:
  name: fluent
---  
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: fluent
spec:
  interval: 1m
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent
  namespace: fluent
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent/fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: fluent
      interval: 1m