---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
data:
  credentials.json: ${DASHAUN_CLOUD_TUNNEL_SECRET}
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
type: Opaque