apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/knative-serving
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  targetNamespace: knative-serving
  timeout: 5m
  wait: true