---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: knative-serving-crds
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./releases/download/knative-v1.10.2/serving-crds.yaml
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: knative-serving
  timeout: 3m0s
  wait: true
