---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: knative-serving
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/knative/serving
