apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-javagrunt-com
  namespace: dev-javagrunt-com
spec:
  interval: 1m
  url: https://github.com/javagrunt-com/flux
  ref:
    branch: keda
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-javagrunt-com
  namespace: dev-javagrunt-com
spec:
  serviceAccountName: dev-javagrunt-com
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev-javagrunt-com
  prune: true