apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: backstage
  namespace: flux-system
spec:
  interval: 1m
  url: https://backstage.github.io/charts  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backstage
  namespace: backstage
spec:
  interval: 5m
  chart:
    spec:
      chart: backstage
      sourceRef:
        kind: HelmRepository
        name: backstage
        namespace: flux-system
      interval: 1m