apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dashaun-live
  namespace: dashaun-live
spec:
  interval: 1m
  url: https://github.com/dashaun-live/flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dashaun-live
  namespace: dashaun-live
spec:
  serviceAccountName: dashaun-live
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dashaun-live
  prune: true