apiVersion: v1
kind: Namespace
metadata:
  name: scdf
---  
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scdf
  namespace: scdf
spec:
  interval: 5m
  chart:
    spec:
      chart: spring-cloud-dataflow
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
      interval: 5m