apiVersion: v1
kind: Namespace
metadata:
  name: concourse
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: concourse-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
spec:
  interval: 5m
  chart:
    spec:
      chart: concourse
      sourceRef:
        kind: HelmRepository
        name: concourse-charts
        namespace: flux-system
      interval: 1m
  values:
    concourse:
      web:
        auth:
          github:
            enabled: true
          mainTeam:
            github:
              user: "dashaun"
        externalUrl: https://kaiju.dashaun.cc
      worker:
        runtime: houdini
    secrets:
      githubClientId: "Ov23liWWfo2u4z49wgjp"
      githubClientSecret: "d59a363031f10b9b47577b29d9f3eec536446095"
