apiVersion: v1
kind: Namespace
metadata:
  name: concourse
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: concourse-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://concourse-charts.storage.googleapis.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: concourse
  namespace: concourse
spec:
  interval: 5m
  chart:
    spec:
      chart: concourse
      sourceRef:
        kind: HelmRepository
        name: concourse-charts
        namespace: flux-system
      interval: 1m
  values:
    concourse:
      web:
        externalUrl: http://concourse.concourse.127.0.0.1.sslip.io
      worker:
        runtime: houdini
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: concourse
  namespace: concourse
spec:
  template:
    spec:
      containers:
        - args:
            - web
          env:
            - name: CONCOURSE_ENABLE_GLOBAL_RESOURCES
              value: "true"
            - name: CONCOURSE_SECRET_RETRY_ATTEMPTS
              value: "5"
            - name: CONCOURSE_SECRET_RETRY_INTERVAL
              value: 1s
            - name: CONCOURSE_LOG_LEVEL
              value: info
            - name: CONCOURSE_BIND_PORT
              value: "8080"
            - name: CONCOURSE_BIND_IP
              value: 0.0.0.0
            - name: CONCOURSE_ADD_LOCAL_USER
              valueFrom:
                secretKeyRef:
                  key: local-users
                  name: concourse-web
            - name: CONCOURSE_EXTERNAL_URL
              value: http://concourse.concourse.127.0.0.1.sslip.io
            - name: CONCOURSE_DEBUG_BIND_IP
              value: 127.0.0.1
            - name: CONCOURSE_DEBUG_BIND_PORT
              value: "8079"
            - name: CONCOURSE_INTERCEPT_IDLE_TIMEOUT
              value: 0m
            - name: CONCOURSE_GLOBAL_RESOURCE_CHECK_TIMEOUT
              value: 1h
            - name: CONCOURSE_RESOURCE_CHECKING_INTERVAL
              value: 1m
            - name: CONCOURSE_RESOURCE_WITH_WEBHOOK_CHECKING_INTERVAL
              value: 1m
            - name: CONCOURSE_CONTAINER_PLACEMENT_STRATEGY
              value: volume-locality
            - name: CONCOURSE_BAGGAGECLAIM_RESPONSE_HEADER_TIMEOUT
              value: 1m
            - name: CONCOURSE_BUILD_TRACKER_INTERVAL
              value: 10s
            - name: CONCOURSE_DB_NOTIFICATION_BUS_QUEUE_SIZE
              value: "10000"
            - name: CONCOURSE_POSTGRES_HOST
              value: concourse-postgresql
            - name: CONCOURSE_POSTGRES_USER
              value: concourse
            - name: CONCOURSE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: concourse-postgresql
            - name: CONCOURSE_POSTGRES_DATABASE
              value: concourse
            - name: CONCOURSE_KUBERNETES_IN_CLUSTER
              value: "true"
            - name: CONCOURSE_KUBERNETES_NAMESPACE_PREFIX
              value: concourse-
            - name: CONCOURSE_GC_INTERVAL
              value: 30s
            - name: CONCOURSE_GC_ONE_OFF_GRACE_PERIOD
              value: 5m
            - name: CONCOURSE_GC_MISSING_GRACE_PERIOD
              value: 5m
            - name: CONCOURSE_AUTH_DURATION
              value: 24h
            - name: CONCOURSE_SESSION_SIGNING_KEY
              value: /concourse-keys/session_signing_key
            - name: CONCOURSE_MAIN_TEAM_LOCAL_USER
              value: test
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CONCOURSE_PEER_ADDRESS
              value: $(POD_IP)
            - name: CONCOURSE_TSA_LOG_LEVEL
              value: info
            - name: CONCOURSE_TSA_BIND_IP
              value: 0.0.0.0
            - name: CONCOURSE_TSA_BIND_PORT
              value: "2222"
            - name: CONCOURSE_TSA_DEBUG_BIND_IP
              value: 127.0.0.1
            - name: CONCOURSE_TSA_DEBUG_BIND_PORT
              value: "2221"
            - name: CONCOURSE_TSA_HOST_KEY
              value: /concourse-keys/host_key
            - name: CONCOURSE_TSA_AUTHORIZED_KEYS
              value: /concourse-keys/worker_key.pub
            - name: CONCOURSE_TSA_HEARTBEAT_INTERVAL
              value: 30s
          image: concourse/concourse:7.11.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /api/v1/info
              port: atc
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 3
          name: concourse-web
          ports:
            - containerPort: 8080
              name: atc
              protocol: TCP
            - containerPort: 2222
              name: tsa
              protocol: TCP
            - containerPort: 8079
              name: atc-debug
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/info
              port: atc
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /concourse-keys
              name: concourse-keys
              readOnly: true
            - mountPath: /concourse-auth
              name: auth-keys
              readOnly: true
      dnsPolicy: ClusterFirst
      initContainers:
        - args:
            - migrate
            - --migrate-to-latest-version
          env:
            - name: CONCOURSE_POSTGRES_HOST
              value: concourse-postgresql
            - name: CONCOURSE_POSTGRES_USER
              value: concourse
            - name: CONCOURSE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: concourse-postgresql
            - name: CONCOURSE_POSTGRES_DATABASE
              value: concourse
          image: concourse/concourse:7.11.2
          imagePullPolicy: IfNotPresent
          name: concourse-migration
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: concourse-web
      volumes:
        - name: concourse-keys
          secret:
            defaultMode: 256
            items:
              - key: host-key
                path: host_key
              - key: session-signing-key
                path: session_signing_key
              - key: worker-key-pub
                path: worker_key.pub
            secretName: concourse-web
        - name: auth-keys
          secret:
            defaultMode: 256
            secretName: concourse-web
