apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-metrics-server
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 1m
  path: ./infrastructure/kube-state-metrics
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  serviceAccountName: kustomize-controller
  timeout: 5m
  wait: true