#apiVersion: v1
#kind: Namespace
#metadata:
#  name: concourse
#---
#apiVersion: source.toolkit.fluxcd.io/v1beta2
#kind: HelmRepository
#metadata:
#  name: concourse-charts
#  namespace: flux-system
#spec:
#  interval: 1m
#  url: https://concourse-charts.storage.googleapis.com/
#---
#apiVersion: helm.toolkit.fluxcd.io/v2
#kind: HelmRelease
#metadata:
#  name: concourse
#  namespace: concourse
#spec:
#  interval: 5m
#  chart:
#    spec:
#      chart: concourse
#      sourceRef:
#        kind: HelmRepository
#        name: concourse-charts
#        namespace: flux-system
#      interval: 1m
#  values:
#    concourse:
#      web:
#        auth:
#          github:
#            enabled: true
#          mainTeam:
#            github:
#              user: "dashaun"
#        clusterName: "Kaiju Pipelines"
#        enableRedactSecrets: true
#        enableAcrossStep: true
#        externalUrl: https://concourse-kaiju.dashaun.live
#        jobSchedulingMaxInFlight: 1
#        kubernetes:
#          enabled: false
#        localAuth:
#          enabled: false
#        vault:
#          enabled: true
#          url: http://vault.vault.svc.cluster.local:8200
#          authBackend: approle
#          useAuthParam: true
#      worker:
#        runtime: houdini