---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  annotations:
    service.cilium.io/global: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    name: grafana
    namespace: grafana