---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: euniceb-org
  name: euniceb-org
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: euniceb-org
  name: euniceb-org
  namespace: euniceb-org
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: euniceb-org
  name: gotk-reconciler
  namespace: euniceb-org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:euniceb-org:reconciler
  - kind: ServiceAccount
    name: euniceb-org
    namespace: euniceb-org