apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: euniceb-org
  namespace: euniceb-org
spec:
  interval: 1m
  url: https://github.com/euniceb-org/flux
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: euniceb-org
  namespace: euniceb-org
spec:
  serviceAccountName: euniceb-org
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: euniceb-org
  prune: true