---
apiVersion: v1
kind: Namespace
metadata:
  name: sample-weblogic-operator-ns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-weblogic-operator-sa
  namespace: sample-weblogic-operator-ns
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weblogic-operator
  namespace: flux-system
spec:
  interval: 1m
  url: https://oracle.github.io/weblogic-kubernetes-operator/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sample-weblogic-operator
  namespace: sample-weblogic-operator-ns
spec:
  interval: 5m
  chart:
    spec:
      chart: weblogic-operator
      serviceAccountName: sample-weblogic-operator-sa
      sourceRef:
        kind: HelmRepository
        name: weblogic-operator
        namespace: flux-system
      interval: 1m    