apiVersion: v1
kind: Namespace
metadata:
  name: korifi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: korifi
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cloudfoundry/korifi
  ref:
    branch: main
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: korifi
  namespace: korifi
spec:
  interval: 5m
  chart:
    spec:
      chart: ./releases/download/v0.11.0/korifi-0.11.0.tgz
      sourceRef:
        kind: GitRepository
        name: korifi
        namespace: flux-system
      interval: 1m
  values:
    generateIngressCertificates: true
    rootNamespace: cf
    adminUserName: cf-admin
    api.apiServer.url: api.cf.dashaun.dev
    defaultAppDomainName: apps.cf.dashaun.dev
    containerRepositoryPrefix: index.docker.io/dashaun/
    kpackImageBuilder.builderRepository: index.docker.io/dashaun/builder